services:
  - type: web
    name: telegram-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python3 bot.py
    envVars:
      - key: BOT_TOKEN
        value: your_telegram_bot_token_here
      - key: GOOGLE_CREDS_PATH
        value: fishmeout-credentials.json
